{% set name = "Unidecode" %}
{% set version = "1.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfdb349d46ed3873ece4586b96aa75258726e2fa8ec21d6f00a591d98806c2f4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<35]
  entry_points:
    - unidecode = unidecode.util:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - unidecode
  commands:
    - unidecode --help

about:
  home: https://pypi.python.org/pypi/Unidecode
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: ASCII transliterations of Unicode text
  dev_url: https://www.tablix.org/~avian/git/unidecode.git

extra:
  recipe-maintainers:
    - synapticarbors
