{% set name = "Unidecode" %}
{% set version = "1.1.1" %}
{% set sha256 = "2b6aab710c2a1647e928e36d69c21e76b453cd455f4e2621000e54b2a9b8cce8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - unidecode = unidecode.util:main

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - unidecode
  commands:
    - unidecode --help

about:
  home: https://pypi.python.org/pypi/Unidecode
  license: GPL-2.0
  license_file: LICENSE
  summary: 'ASCII transliterations of Unicode text'
  dev_url: https://www.tablix.org/~avian/git/unidecode.git

extra:
  recipe-maintainers:
    - synapticarbors
