{% set name = "Unidecode" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce35985008338b676573023acc382d62c264f307c8f7963733405add37ea2b23

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - unidecode = unidecode.util:main
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

# E   UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 0: invalid start byte
# Tests not adapted for win
{% set deselect_tests = "" %}
{% set deselect_tests = " --deselect=tests/test_utility.py::TestUnidecodeUtility::test_commandline" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_utility.py::TestUnidecodeUtility::test_encoding_error" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_utility.py::TestUnidecodeUtility::test_file_default_encoding" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_utility.py::TestUnidecodeUtility::test_file_specified_encoding" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_utility.py::TestUnidecodeUtility::test_file_stdin" %}  # [win]
test:
  source_files:
    - tests
  imports:
    - unidecode
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - unidecode --help
    - pytest -v tests {{ deselect_tests }}

about:
  home: https://pypi.org/project/Unidecode
  license: GPL-2.0-or-later
  license_file: LICENSE
  license_family: GPL
  summary: ASCII transliterations of Unicode text
  description: |
    It often happens that you have text data in Unicode, but you need to represent it in ASCII. For example when integrating with legacy code that doesn't support Unicode, or for ease of entry of non-Roman names on a US keyboard, or when constructing ASCII machine identifiers from human-readable Unicode strings that should still be somewhat intelligible. A popular example of this is when making an URL slug from an article title.
  dev_url: https://github.com/avian2/unidecode
  doc_url: https://github.com/avian2/unidecode/blob/master/README.rst

extra:
  recipe-maintainers:
    - avian2
