travis:
  secure:
    BINSTAR_TOKEN: Po64hERl7GUDpTgDvZj2l1OjCGwZoWChhpSnJpvedxJHjU9SRqqG4BmDL4FrkWaEAAOE+GDgdJaAohn0aK1wVNi4APsuP1Qla4h5vNGoaayQMW+Iid0cdtxl05Is/ImaynDMhrVGpNUbqs/3RYUjqsa+Y6tVdXZuR3RiWzv4DKYOdqy33nxA12GJ97GSmAogYqNIDE0QgCl/f9GLjMwc/eDqZ5cUVXbEyPMEylDzm3sVyipOYN9/IxzhlI8qLQu/AFPuXTORlYD2Wm+2QsXsp+Q4nYA3WN4zaZz25jJwydzLfRPuHfX22+1exG3wrpmvzLOA/GwC6L3qqU/iEMMVXPqNTaGYzv1HGV9dQaWuXGfffC50OAMTxnpdb5bI17AjqOMYgc7TVpbpmsiqN1m18UPy0fftq8B6/CaOd0rgHpl0EbWxP7I2NN0eYdD/NwAoO4YwhSzc3t0TqRomWBmLbHmhUtFwtTS05aPJ08f+aQGE9A+eRi+CRDSjXS0dkomm53T7T26TDbaRctukT07OXU7ycRg1kWpM8RHV+dkF+UvBW4QbYEO541TATY4S08xm1uYzlJ9aEaRch+2+SuG1yhgBHPpvtv3Ry3AvAgHxiDnxwPk9f4/EK3spYYu3+miCikV0BtnZT+pAdLN58tydYTrpoLzc8tEnkVqlf7olGbM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
