travis:
  secure:
    BINSTAR_TOKEN: bPgBU5xVGeGrwHqk6e3Z7daF39Ov/Eh7dp9CpE44vI38FC54NWxtvWL5ZDXu0uTUxroFLFzgfuqeP8hsOZArLRcYPERbDKssULJi2pUw7c9un7rpRhmks7A24OfXEx/pgkeFJHQE6m7OXqL0QIkb5xd2hOXzDhCQDwiocuQVEbPiqDDQYWeCaYZRduCmcSE864DplN+375OVwVFurvrSMB5dOLSY/j7bcEJpOthn9ln9wLVg50jbjYkOu0SMUd/lziIS3nW6V7dEIrX2CunQa7Ks7aDariD0VNEUcbbHbNEYbomlopf133Og58pScT+Dhe+iLMieGUNfz3sQg4E8sDlpg41CcRXDz8j5MvGbUmhqm+eESXy68gggS5uFlwTE2WA46m5mGyqliTWc3tavKCt8Ume6rIH/LjQ0/3PEAaVUAM0x3bNZJU/wRFnz0x/973c4Wkb9fQqe2Cic2wmbpJCJ9hNS8hjLBn8ugKcM/Bd6wl1oi1kmiWyxgYAxzwFn9CcIZJevy0faHpE+f6kHVh6DaohtpQ9ulxUh9o3L7Mz7RfParjdHZ6GdwokBgDgp2paXug/mmsTuiIU448VCqxf4JjjH8bwWRSiFzUqXeK+OyVCbdGMJhCFUfsLWj5G0OHAek/82SysULIgysm4TSBxBbcnXKG2YKDGX1UCv5nE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
